'use strict';

const CLIENT_READY = 'CLIENT_READY';
const PRODUCER_READY = 'PRODUCER_READY';
const SUBSCRIPTION_READY = 'SUBSCRIPTION_READY';
const CONSUMER_READY = 'CONSUMER_READY';
const PRODUCER_ERROR = 'PRODUCER_ERROR';
const TOPICS_READY = 'TOPICS_READY';
const SUBSCRIBE_CONSUMER_LOADED = 'SUBSCRIBE_CONSUMER_LOADED';
const CONSUMER_CONNECT = 'CONSUMER_CONNECT';
const ALL_CONSUMER_CONNECT = 'ALL_CONSUMER_CONNECT';
const PRINT_LOGGER = 'PRINT_LOGGER';
const PRINT_ERROR_LOGGER = 'PRINT_ERROR_LOGGER';
const START_READY = 'START_READY';
const CLOSE_ALL_CONSUMER = 'CLOSE_ALL_CONSUMER';
module.exports = {
  CLIENT_READY,
  PRODUCER_READY,
  PRODUCER_ERROR,
  CONSUMER_READY,
  SUBSCRIPTION_READY,
  TOPICS_READY,
  SUBSCRIBE_CONSUMER_LOADED,
  CONSUMER_CONNECT,
  ALL_CONSUMER_CONNECT,
  PRINT_LOGGER,
  PRINT_ERROR_LOGGER,
  START_READY,
  CLOSE_ALL_CONSUMER,
};
